server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/zhao?serverTimezone=UTC
  application:
    name: service-providers

mybatis:
  type-aliases-package: com.serviceproviders.pojo


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka